backend_purrsuit/config/routes.rb
Rails.application.routes.draw do
  get 'users/all' => 'users#all', format: :json
  get 'users/new' => 'users#new'
  post 'users/create' => 'users#create', format: :json
  get 'users/:id' => 'users#show', format: :json
  post 'users/update' => 'users#update', format: :json, as: :users_update
  delete 'users/delete/:id' => 'users#delete', as: :users_delete

  get 'deputies/all' => 'deputies#all', format: :json
  get 'deputies/:id' => 'deputies#show', format: :json
  get 'deputies/search/:toSearch' => 'deputies#search', format: :json
  delete 'deputies/:id' => 'deputies#delete', as: :deputies_delete

  get 'gamifications/all' => 'gamifications#all', format: :json
  get 'gamification/:id' => 'gamifications#show', as: :show_gamification


  get 'achievements/all' => 'achievements#all', format: :json, as: :achievements_all
  get 'achievements/new' => 'achievements#new', format: :json, as: :achievements_new
  post 'achievements/create' => 'achievements#create', as: :achievements
  get 'achievements/:id' => 'achievements#show', format: :json
  get 'achievements/:id/edit' => 'achievements#edit', format: :json, as: :achievements_edit
  put 'achievements/:id/update' => 'achievements#update',as: :achievements_update
	delete 'achievements/:id' => 'achievements#delete', as: :achievements_delete

  get 'quests/all' => 'quests#all', format: :json, as: :quests_all
	get 'quests/new' => 'quests#new', format: :json, as: :quests_new
	post 'quests/create' => 'quests#create', as: :quests
	get 'quests/:id' => 'quests#show', format: :json
	put 'quests/:id/update' => 'quests#update', format: :json, as: :quests_update
	get 'quests/:id/edit' => 'quests#edit', format: :json, as: :quests_edit
	delete 'quests/:id' => 'quests#delete', as: :quests_delete


	get 'ufs/all' => 'ufs#all', format: :json
	get 'ufs/new' => 'ufs#new'
 	post 'ufs/create' => 'ufs#create', as: :ufs
	get 'ufs/:id' => 'ufs#show', format: :json
	patch 'ufs/:id/update' => 'ufs#update', format: :json, as: :uf
	get 'ufs/:id/edit' => 'ufs#edit'
	delete 'ufs/:id' => 'ufs#delete', as: :ufs_delete

	get 'parties/all' => 'parties#all', format: :json
	get 'parties/new' => 'parties#new'
	post 'parties/create' => 'parties#create', as: :parties
	get 'parties/:id' => 'parties#show', format: :json
	patch 'parties/:id/update' => 'parties#update', format: :json, as: :party
	get 'parties/:id/edit' => 'parties#edit'
	delete 'parties/:id' => 'parties#delete', as: :parties_delete

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/signin' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
end

backend_purrsuit/app/models/achievement.rb
class Achievement < ActiveRecord::Base
	acts_as :gamification

end

backend_purrsuit/app/controllers/achievement_controller.rb
class AchievementController < ApplicationController

	def all
		@achievement = Achievement.all

		respond_to do |format|
			format.html
			format.json {render json: @achievement}
		end
	end

	def show
		render json: Achievement.find(params[:id])
	end

	def new
		@achievement = Achievement.new
	end

	def create
		@achievement = Achievement.new(achievement_params)
		if @achievement.save
			redirect_to :achievements_all
		end
	end

	def edit
		@achievement = Achievement.find(params[:id])
		render 'edit'
	end

	def update
		@achievement = Achievement.find(params[:id])
		if @achievement.update(achievement_params)
			redirect_to :achievements_all
		else
			render 'edit'
		end
	end

	def delete
		id_achievement = params[:id]
		achievements = Achievement.where(id: id_achievement)
		achievement = achievements.first
		achievement.destroy
		redirect_to :achievements_all

	end

	private

	def achievement_params
		params.require(:achievement).permit(:name, :experience_points, :description)
	end
end

backend_purrsuit/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

	def all
		@achievement = Achievement.all

		respond_to do |format|
			format.html
			format.json {render json: @achievement}
		end
	end

	def show
		render json: Achievement.find(params[:id])
	end

	def new
		@achievement = Achievement.new
	end

	def create
		@achievement = Achievement.new(achievement_params)
		if @achievement.save
			redirect_to :achievements_all
		end
	end

	def edit
		@achievement = Achievement.find(params[:id])
		render 'edit'
	end

	def update
		@achievement = Achievement.find(params[:id])
		if @achievement.update(achievement_params)
			redirect_to :achievements_all
		else
			render 'edit'
		end
	end

	def delete
		id_achievement = params[:id]
		achievements = Achievement.where(id: id_achievement)
		achievement = achievements.first
		achievement.destroy
		redirect_to :achievements_all

	end

	private

	def achievement_params
		params.require(:achievement).permit(:name, :experience_points, :description)
	end
end

backend_purrsuit/app/views/achievement/all.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= stylesheet_link_tag "stylesheet.css" %>
	</head>
	<body>
		<div class="principalSquare">
			<ul class="nav nav-pills">
      	<li role="presentation"><%= link_to "Início", login_path %></li>
				<li role="presentation" class="active"><a href="#">Achievement</a></li>
				<li role="presentation"><%= link_to "Quests", :quests_all%></li>
			</ul>
			<%= button_to "New Achievement", :achievements_new, :class => "btn btn-default btn-lg create_button", :method => :get%>
			<div class="listSquare">
				<% @achievement.each do | a | %>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title"><%= a.name %></h3>
							<span class="label label-default">Achievement</span>
						</div>
						<div class="panel-body">
							<%= a.description%><br>
							<div class="btn-toolbar button_group" role="group">	
								<%= button_to "Edit", achievements_edit_path(a), :method => :get, :class => "option_button btn btn-default btn-xs" %>
								<%= button_to "Delete", achievements_delete_path(a), :method => :delete, :class => "option_button btn btn-default btn-xs" %>
							</div>
						</div>
					</div>
        		<% end %>
     		 </div>
		</div>
	</body>
</html>

backend_purrsuit/app/views/achievement/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
      <ul class="nav nav-pills">
        <li role="presentation"><a href="#">Início</a></li>
       <li role="presentation" class="active"><%= link_to "Achievements", :achievements_all%></li>
        <li role="presentation"><a href="#">Quests</a></li>
      </ul>
      <div class="listSquare">
        <%= form_for :achievement, url: achievements_update_path, method: :put do | form | %>
          <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Achievement's name"%>
          <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
          <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
          <%= form.submit "Edit Achievement", :class => "gamification_button btn btn-default btn-lg"%>
        <% end %> 
        <%= button_to "Cancel", :quests_all, :class => "btn btn-default btn-lg gamification_button", :method => :get %>
      </div>
    </div>
  </body>
</html>

backend_purrsuit/app/views/achievement/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
   <div class="principalSquare">
      <ul class="nav nav-pills">
   	   <li role="presentation"><%= link_to "Início", login_path %></li>
        <li role="presentation" class="active"><a href="#">Achievement</a></li>
        <li role="presentation"><%= link_to "Quests", :quests_all%></li>
      </ul>
      <div class="listSquare">
				<%= form_for(@achievement) do | form | %>
     		  <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Achievement's name"%>
   			  <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%> 
    		  <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %> 
  		    <%= form.submit "Create Achievement", :class => "gamification_button btn btn-default btn-lg"%>
		    <% end %>
        <%= button_to "Cancel", :achievements_all, :class => "btn btn-default btn
-lg gamification_button", :method => :get %>
      </div>
    </div>
  </body>
</html>

backend_purrsuit/app/views/achievement/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1><%= @achievement.name %></h1>
    <h3><%= @achievement.experience_points %></h3>
    <h5><%= @achievement.description %></h3>
  </body>
</html>