config/routes.rb
Rails.application.routes.draw do
  get 'users/all' => 'user#all', format: :json
  get 'users/new' => 'user#new'
  post 'users/create' => 'user#create', format: :json
  get 'users/:id' => 'user#show', format: :json
  get 'users/:id/update' => 'user#update', format: :json, as: :users_update
  delete 'users/:id' => 'user#delete', as: :users_delete

  get 'deputies/all' => 'deputy#all', format: :json
  get 'deputies/:id' => 'deputy#show', format: :json
  delete 'deputies/:id' => 'deputy#delete', as: :deputies_delete



	get 'gamifications/all' => 'gamification#all', format: :json

	get 'achievements/all' => 'achievement#all', format: :json
	get 'achievements/new' => 'achievement#new', format: :json, as: :achievements_new
	post 'achievements/create' => 'achievement#create', as: :achievements
	get 'achievements/:id' => 'achievement#show', format: :json
  get 'achievements/:edit' => 'achievement#edit', format: :json
  patch 'achievements/:update' => 'achievement#update'

	get 'quests/all' => 'quest#all', format: :json
	get 'quests/new' => 'quest#new', format: :json, as: :quests_new
	post 'quests/create' => 'quest#create', as: :quests
	get 'quests/:id' => 'quest#show', format: :json
	put 'quests/:id/update' => 'quest#update', format: :json, as: :quests_update
	get 'quests/:id/edit' => 'quest#edit', format: :json, as: :quests_edit
	delete 'quests/:id' => 'quest#delete'

	get 'ufs/all' => 'uf#all', format: :json
	get 'ufs/new' => 'uf#new'
  post 'ufs/create' => 'uf#create', as: :ufs
	get 'ufs/:id' => 'uf#show', format: :json
	patch 'ufs/:id/update' => 'uf#update', format: :json, as: :uf
	get 'ufs/:id/edit' => 'uf#edit'
	delete 'ufs/:id' => 'uf#delete', as: :ufs_delete

	get 'parties/all' => 'party#all', format: :json
	get 'parties/new' => 'party#new'
	post 'parties/create' => 'party#create', as: :parties
	get 'parties/:id' => 'party#show', format: :json
	patch 'parties/:id/update' => 'party#update', format: :json, as: :party
	get 'parties/:id/edit' => 'party#edit'
	delete 'parties/:id' => 'party#delete', as: :parties_delete

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
end

app/models/cabinet.rb
class Cabinet < ActiveRecord::Base
  # has_many :deputy

  validates :annex, presence: true
  validates :number, presence: true
end

app/models/deputy.rb
require "net/http"
require "uri"
require "nokogiri"

class Deputy < ActiveRecord::Base
  acts_as :person
  belongs_to :uf

  # validates_numericality_of :age
  # validates_numericality_of :registration

  # validates :name, presence: true, length: {maximum: 50}
  # validates :age, presence: true
  # validates :gender, presence: true
  # validates :registration, presence: true, uniqueness: true
  # validates :legislation_situation, presence: true, length: {maximum: 100}


  def self.parse_deputies
    Uf.populate_ufs
    Party.parse_parties

    url = URI.parse("http://www.camara.gov.br/SitCamaraWS/Deputados.asmx/ObterDeputados")
    request = Net::HTTP::Get.new(url.to_s)
    response = Net::HTTP.start(url.host, url.port) {|http|
      http.request(request)
    }
    xml_doc = Nokogiri::XML(response.body)
    xml_doc.xpath("//deputado").each do |d|
      ideCadastro = d.elements[0].text.to_s
      condicao = d.elements[2].text.to_s
      matricula = d.elements[3].text.to_s
      idParlamentar = d.elements[4].text.to_s
      nome = d.elements[5].text.to_s
      nomeParlamentar = d.elements[6].text.to_s
      urlFoto = d.elements[7].text.to_s
      sexo = d.elements[8].text.to_s
      uf = d.elements[9].text.to_s
      partido = d.elements[10].text.to_s
      fone = d.elements[13].text.to_s
      email = d.elements[14].text.to_s
      annexo = d.elements[12].text.to_s
      gabinete = d.elements[11].text.to_s


      deputy = Deputy.new(
                            :name => nome,
                            :deputy_name => nomeParlamentar,
                            :gender => sexo,
                            :email => email,
                            :image_path => urlFoto,
                            :registration => matricula,
                            :legislation_situation => condicao
                            )
      if deputy.save
        Uf.find_by_initials(uf).add_deputy(deputy)
        Party.find_by_initials(partido).add_deputy(deputy)
        puts "Deputado " + nomeParlamentar + " salvo."
      end
    end
  end
  # (:name,:gender,:email,:age,:registration,:legislation_situation)
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as :person

  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX	=	/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save { self.email = email.downcase }
  validates :email, presence: true

  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/achievement_controller.rb
class AchievementController < ApplicationController

	def all
		@achievement = Achievement.all

		respond_to do |format|
			format.html
			format.json {render json: @achievement}
		end
	end

	def show
		render json: Achievement.find(params[:id])
	end

	def new
		@achievement = Achievement.new
	end

	def create
		@achievement = Achievement.new(achievement_params)
		if @achievement.save
			redirect_to :achievements_all
		end
	end

	def edit
		@achievement = Achievement.find(params[:id])
		render 'edit'
	end

	def update
		@achievement = Achievement.find(params[:id])
		if @achievement.update(achievement_params)
			redirect_to @achievement
		else
			render 'edit'
		end
	end

	def delete
		id_achievement = params[:id]
		achievements = Achievement.where(id: id_achievement)
		achievement = achievements.first
		achievement.destroy
		redirect_to :gamifications_all
	end

	private

	def achievement_params
		params.require(:achievement).permit(:name, :experience_points, :description)
	end
end

app/controllers/quest_controller.rb
class QuestController < ApplicationController

	def all
		@quest = Quest.all

		respond_to do |format|
			format.html
			format.json {render json: @quest}
		end
	end

	def show
		render json: Quest.find(params[:id])
	end

	def new
		@quest = Quest.new
	end

	def create
		@quest = Quest.new(quest_params)
		if @quest.save
			redirect_to :quests_all
		else
			render 'new'
		end
	end

	def edit

		@quest = Quest.find(params[:id])
		render 'edit'

	end

	def update
		@quest = Quest.find(params[:id])

		if @quest.update(quest_params)
			redirect_to :quests_all
		else
			render 'edit'
		end
	end

	def delete
		id_quest = params[:id]
		quests = Quest.where(id: id_quest)
		quest = quests.first
		quest.destroy
		redirect_to :gamifications_all
	end

	
	private

	def quest_params
		params.require(:quest).permit(:name, :experience_points, :description)
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def all
    render json: User.all
  end

  def show
    id_users = params[:id]
        users = User.where(id: id_users)
          user = nil
        if (users.length > 0)
            user = users.first
        else
            raise "error"
        end
        render json: user
  end

  def new
    user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
        render json: user
      else
        render action: :new
end
  end

  def edit
    id_users = params[:id]
    user = nil
    users = User.where(id: id_users)
      @user = users.first
      render :edit
  end

  def update
    id_users = params[:id]
    users = User.where(id: id_users)
    user = users.first
        user.update(users_params)
        render json: user
  end

  def delete
    id_user = params[:id]
    users = User.where(id: id_user)
    user = users.first
    user.destroy
      redirect_to :users_all
  end

  private
  def user_params
        params.require(:user).permit(:nome,:email,:password)
    end
end

app/views/achievement/all.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
      <ul class="nav nav-pills">
        <li role="presentation"><a href="#">Início</a></li>
        <li role="presentation" class="active"><a href="#">Achievement</a></li>
        <li role="presentation"><%= link_to "Quests", :quests_all%></li>
      </ul>
			<%= button_to "New Achievement", :achievements_new, :class => "btn btn-default btn-lg create_button", :method => :get%>
      <div class="listSquare">
        <% @achievement.each do | a | %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%= a.name %></h4>
                <span class="label label-default">Achievement</span>
            </div>
            <div class="panel-body">
              <%= a.description%><br>
							<div class="btn-toolbar button_group" role="group">	
             		 <%= button_to "Edit", achievements_path(a), :method => :get, :class => "option_button btn btn-default btn-xs" %>
             		 <%= button_to "Delete", achievements_path(a), :method => :delete, :class => "option_button btn btn-default btn-xs" %>
							</div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/achievement/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
      <ul class="nav nav-pills">
        <li role="presentation"><a href="#">Início</a></li>
        <li role="presentation" class="active"><a href="#">Achievement</a></li>
        <li role="presentation"><%= link_to "Quests", :quests_all%></li>
      </ul>
      <div class="listSquare">
				<%= form_for(@achievement) do | form | %>
     		  <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Achievement's name"%>
   			  <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%> 
    		  <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %> 
  		    <%= form.submit "Create Achievement", :class => "gamification_button btn btn-default btn-lg"%>
		    <% end %>
        <%= button_to "Cancel", :achievements_all, :class => "btn btn-default btn
-lg gamification_button", :method => :get %>
      </div>
    </div>
  </body>
</html>

app/views/quest/all.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
      <ul class="nav nav-pills">
        <li role="presentation"><a href="#">Início</a></li>
        <li role="presentation"><%= link_to "Achievements", :achievements_all%></li>
				<li role="presentation" class="active"><a href="#">Quests</a></li>
      </ul>
      <%= button_to "New Quest", :quests_new, :class => "btn btn-default btn-lg create_button", :method => :get%>
      <div class="listSquare">
        <% @quest.each do | q | %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%= q.name %></h4>
                <span class="label label-default">Quest</span>
            </div>
            <div class="panel-body">
              <%= q.description%>
              <div class="btn-toolbar button_group" role="group"> 
                <%= button_to "Edit", quests_edit_path(q), :method => :get, :class => "option_button btn btn-default btn-xs" %>
                <%= button_to "Delete", quests_delete_path(q), :method => :delete, :class => "option_button btn btn-default btn-xs" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/quest/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
      <ul class="nav nav-pills">
        <li role="presentation"><a href="#">Início</a></li>
        <li role="presentation" class="active"><%= link_to "Achievements", :achievements_all%></li>
        <li role="presentation"><a href="#">Quests</a></li>
      </ul>
      <div class="listSquare">
        <%= form_for(@quest) do | form | %>
          <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Quest's name"%>
          <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
          <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
          <%= form.submit "Create Achievement", :class => "gamification_button btn btn-default btn-lg"%>
        <% end %>
        <%= button_to "Cancel", :achievements_all, :class => "btn btn-default btn
-lg gamification_button", :method => :get %>
      </div>
    </div>
  </body>
</html>