backend_purrsuit/config/routes.rb
Rails.application.routes.draw do
  get 'users/all' => 'users#all', format: :json
  get 'users/new' => 'users#new'
  post 'users/create' => 'users#create', format: :json
  get 'users/:id' => 'users#show', format: :json
  post 'users/update' => 'users#update', format: :json, as: :users_update
  delete 'users/delete/:id' => 'users#delete', as: :users_delete

  get 'deputies/all' => 'deputies#all', format: :json
  get 'deputies/:id' => 'deputies#show', format: :json
  get 'deputies/search/:toSearch' => 'deputies#search', format: :json
  delete 'deputies/:id' => 'deputies#delete', as: :deputies_delete

  get 'gamifications/all' => 'gamifications#all', format: :json
  get 'gamification/:id' => 'gamifications#show', as: :show_gamification


  get 'achievements/all' => 'achievements#all', format: :json, as: :achievements_all
  get 'achievements/new' => 'achievements#new', format: :json, as: :achievements_new
  post 'achievements/create' => 'achievements#create', as: :achievements
  get 'achievements/:id' => 'achievements#show', format: :json
  get 'achievements/:id/edit' => 'achievements#edit', format: :json, as: :achievements_edit
  put 'achievements/:id/update' => 'achievements#update',as: :achievements_update
	delete 'achievements/:id' => 'achievements#delete', as: :achievements_delete

  get 'quests/all' => 'quests#all', format: :json, as: :quests_all
	get 'quests/new' => 'quests#new', format: :json, as: :quests_new
	post 'quests/create' => 'quests#create', as: :quests
	get 'quests/:id' => 'quests#show', format: :json
	put 'quests/:id/update' => 'quests#update', format: :json, as: :quests_update
	get 'quests/:id/edit' => 'quests#edit', format: :json, as: :quests_edit
	delete 'quests/:id' => 'quests#delete', as: :quests_delete


	get 'ufs/all' => 'ufs#all', format: :json
	get 'ufs/new' => 'ufs#new'
 	post 'ufs/create' => 'ufs#create', as: :ufs
	get 'ufs/:id' => 'ufs#show', format: :json
	patch 'ufs/:id/update' => 'ufs#update', format: :json, as: :uf
	get 'ufs/:id/edit' => 'ufs#edit'
	delete 'ufs/:id' => 'ufs#delete', as: :ufs_delete

	get 'parties/all' => 'parties#all', format: :json
	get 'parties/new' => 'parties#new'
	post 'parties/create' => 'parties#create', as: :parties
	get 'parties/:id' => 'parties#show', format: :json
	patch 'parties/:id/update' => 'parties#update', format: :json, as: :party
	get 'parties/:id/edit' => 'parties#edit'
	delete 'parties/:id' => 'parties#delete', as: :parties_delete

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/signin' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
end

backend_purrsuit/app/models/quest.rb
class Quest < ActiveRecord::Base
	acts_as :gamification

end

backend_purrsuit/app/controllers/quest_controller.rb
class QuestController < ApplicationController

	def all
		@quest = Quest.all

		respond_to do |format|
			format.html
			format.json {render json: @quest}
		end
	end

	def show
		render json: Quest.find(params[:id])
	end

	def new
		@quest = Quest.new
	end

	def create
		@quest = Quest.new(quest_params)
		if @quest.save
			redirect_to :quests_all
		else
			render 'new'
		end
	end

	def edit

		@quest = Quest.find(params[:id])
		render 'edit'

	end

	def update
		@quest = Quest.find(params[:id])

		if @quest.update(quest_params)
			redirect_to :quests_all
		else
			render 'edit'
		end
	end

	def delete
		id_quest = params[:id]
		quests = Quest.where(id: id_quest)
		quest = quests.first
		quest.destroy
		redirect_to :quests_all
	end

	
	private

	def quest_params
		params.require(:quest).permit(:name, :experience_points, :description)
	end
end

backend_purrsuit/app/controllers/quests_controller.rb
class QuestsController < ApplicationController

	def all
		@quest = Quest.all

		respond_to do |format|
			format.html
			format.json {render json: @quest}
		end
	end

	def show
		render json: Quest.find(params[:id])
	end

	def new
		@quest = Quest.new
	end

	def create
		@quest = Quest.new(quest_params)
		if @quest.save
			redirect_to :quests_all
		else
			render 'new'
		end
	end

	def edit

		@quest = Quest.find(params[:id])
		render 'edit'

	end

	def update
		@quest = Quest.find(params[:id])

		if @quest.update(quest_params)
			redirect_to :quests_all
		else
			render 'edit'
		end
	end

	def delete
		id_quest = params[:id]
		quests = Quest.where(id: id_quest)
		quest = quests.first
		quest.destroy
		redirect_to :quests_all
	end


	private

	def quest_params
		params.require(:quest).permit(:name, :experience_points, :description)
	end
end

backend_purrsuit/app/views/quest/all.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
		<ul class="nav nav-pills">
		  <li role="presentation"><%= link_to "Início", login_path %></li>
			<li role="presentation"><%= link_to "Achievements", :achievements_all%></li>
			<li role="presentation" class="active"><a href="#">Quests</a></li>
      </ul>
      <%= button_to "New Quest", :quests_new, :class => "btn btn-default btn-lg create_button", :method => :get%>
      <div class="listSquare">
			<% @quest.each do | q | %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%= q.name %></h4>
                <span class="label label-default">Quest</span>
            </div>
            <div class="panel-body">
              <%= q.description%>
              <div class="btn-toolbar button_group" role="group"> 
                <%= button_to "Edit", quests_edit_path(q), :method => :get, :class => "option_button btn btn-default btn-xs" %>
                <%= button_to "Delete", quests_delete_path(q), :method => :delete, :class => "option_button btn btn-default btn-xs" %>
              </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </body>
</html>

backend_purrsuit/app/views/quest/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
      <ul class="nav nav-pills">
        <li role="presentation"><a href="#">Início</a></li>
       <li role="presentation"><%= link_to "Achievements", :achievements_all%></li>
        <li role="presentation" class="active"><a href="#">Quests</a></li>
      </ul>
      <div class="listSquare">
        <%= form_for :quest, url: quests_update_path, method: :put do | form | %>
          <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Quest's name"%>
          <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
          <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
          <%= form.submit "Edit Quest", :class => "gamification_button btn btn-default btn-lg"%>
        <% end %> 
        <%= button_to "Cancel", :quests_all, :class => "btn btn-default btn
-lg gamification_button", :method => :get %>
      </div>
    </div>
  </body>
</html>

backend_purrsuit/app/views/quest/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "stylesheet.css" %>
  </head>
  <body>
    <div class="principalSquare">
      <ul class="nav nav-pills">
	      <li role="presentation"><%= link_to "Início", login_path %></li>
      	<li role="presentation"><%= link_to "Achievements", :achievements_all%></li>
        <li role="presentation" class="active"><a href="#">Quests</a></li>
      </ul>
      <div class="listSquare">
        <%= form_for(@quest) do | form | %>
          <%= form.text_field :name, :class => "gamification_fields", :placeholder => "Quest's name"%>
          <%= form.number_field :experience_points, :class => "gamification_fields", :placeholder => "Experience Points"%>
          <%= form.text_field :description, :class => "gamification_fields", :placeholder => "Description" %>
          <%= form.submit "Create Quest", :class => "gamification_button btn btn-default btn-lg"%>
        <% end %>
        <%= button_to "Cancel", :quests_all, :class => "btn btn-default btn
-lg gamification_button", :method => :get %>
      </div>
    </div>
  </body>
</html>

backend_purrsuit/app/views/quest/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @quest.name %>
</p>
  <strong>Description:</strong>
  <%= @quest.description %>
</p>

<p>
<strong>Experience:</strong>
<%= @quest.experience_points %>
</p>

<%= button_to 'Delete', quests_delete_path , method: :delete %>
<%= button_to 'Delete', quests_delete_path , method: :delete %>